// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:647eed9d-b309-46ef-b215-ea0566ab00bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jyNTGr5DV",
    "aws_user_pools_web_client_id": "5qohojihsk7gm89elu34585tij",
    "oauth": {},
    "aws_user_files_s3_bucket": "tag-this-app-ad-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
